{
 "title": "New dashboard Copy",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Method execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(method_execution_duration{instance=\"$Instance\"}[1m])) by (method_name) / sum(increase(method_execution_count{instance=\"$Instance\"}[1m])) by (method_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_sum{instance=\"$Instance\"}[1m])) by (action) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5XX Endpoint 1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{code=~\"5..\", instance=\"$Instance\"}[1m])) by (action)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5XX % 30m",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code=~\"5..\", instance=\"${Instance}\"}[1m])) / sum(rate(http_requests_received_total{instance=\"${Instance}\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPM by Instance 1m",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_received_total{instance=\"${Instance}\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}